### ISSUE TITLE
Unexpected exception[RuntimeException: Couldn't open network interface empty

### ISSUE THREAD

**Issue by adis-me** [kristian-lange/net-glimpse#1]
Reproduction steps:

1. Download zip file
2. Extract
3. Fix permissions ./bin/net-glimpse
4. run `./bin/net-glimpse -Dhttp.port=9001`
5. Go to `http://localhost:9001` and you will see a blank screen, logs:

```
[info] play.api.Play - Application started (Prod)
[info] p.c.s.NettyServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9001
[info] o.p.core.Pcaps - 13 NIF(s) found.
[error] application - 

! @74jld8p16 - Internal server error, for (GET) [/netdata] ->
 
play.api.UnexpectedException: Unexpected exception[RuntimeException: Couldn't open network interface empty]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:289)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:220)
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:100)
	at play.core.server.netty.PlayRequestHandler$$anonfun$handle$1.applyOrElse(PlayRequestHandler.scala:129)
	at play.core.server.netty.PlayRequestHandler$$anonfun$handle$1.applyOrElse(PlayRequestHandler.scala:127)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:346)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:345)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
Caused by: java.lang.RuntimeException: Couldn't open network interface empty
	at services.PcapInitializer.openPcap(PcapInitializer.java:97)
	at services.PcapInitializer.getPcapDispatcherActorRef(PcapInitializer.java:80)
	at controllers.HomeController.netdata(HomeController.java:30)
	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$5$$anonfun$apply$5.apply(Routes.scala:213)
	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$5$$anonfun$apply$5.apply(Routes.scala:213)
	at play.core.j.JavaWebSocket$$anonfun$ofJson$1.apply(JavaWebSocket.scala:107)
	at play.core.j.JavaWebSocket$$anonfun$ofJson$1.apply(JavaWebSocket.scala:107)
	at play.core.j.JavaWebSocket$$anonfun$webSocketWrapper$1.apply(JavaWebSocket.scala:34)
	at play.core.j.JavaWebSocket$$anonfun$webSocketWrapper$1.apply(JavaWebSocket.scala:28)
	at play.api.mvc.WebSocket$$anon$1.apply(WebSocket.scala:43)
[info] s.NifDispatcherActor - registered WebSocket actor to network interface empty
```

What am I doing wrong?

**Comment by kristian-lange** [comment]
You have to specify the network interface with the 'nif' query parameter. E.g. if you want to intercept the network interface 'en0' you would use the URL `http://localhost:9001/?nif=en0`. Without specifying the network interface net-glimpse tries to open the interface 'empty' which obviously doesn't exist. This is actually all what this log `play.api.UnexpectedException: Unexpected exception[RuntimeException: Couldn't open network interface empty]` is saying: couldn't open interface with the name 'empty'.
